contentdir: "content"
languageCode: "en-us"
layoutdir: "layouts"
publishdir: "public"
Paginate: 10
indexes:
  category: "categories"
baseurl: "http://soloc.github.io/hugo_gh_blog"
title: "Just a memo"
canonifyurls: true
theme: "purehugo"
